### ISSUE TITLE
Where is a italian language??

### ISSUE THREAD

**Issue by crensyhanilas** [Sudomemo/sudomemo-locales#117]
i live in Italy, but i speak italian.

**Comment by sudofox** [comment]
You are welcome to contribute an Italian translation - instructions are in the README.md file. The locale code would be `it_IT`

**Comment by crensyhanilas** [comment]
I do not have a computer. on android will installed "QuickEdit".

**Comment by sudofox** [comment]
Alright, sounds good. I'm going to close this issue; if you have other questions feel free to reach out on Discord

**Comment by crensyhanilas** [comment]
I'm Harder and could be finished for the italian language.

**Comment by crensyhanilas** [comment]
i've Added this pull request because i finished working.
