### ISSUE TITLE
There is no mobile app.

### ISSUE THREAD

**Issue by crensyhanilas** [Sudomemo/sudomemo-locales#119]
How can i download on google play? Seatching "sudomemo" and cannot find it. Please reply for austin burk (sudofox)

**Comment by SnowpMakes** [comment]
The is no app Sudomemo app availiable at the moment. The only way to post flipnotes is on your Nintendo DSi and the only ways to view flipnotes is on your DSi and on the [sudomemo website](https://sudomemo.net).

**Comment by crensyhanilas** [comment]
You need to install android studio.

**Comment by SnowpMakes** [comment]
You need to tell that to @sudofox, I don’t develop this and it’s up to him to make an app

**Comment by sudofox** [comment]
Please don't use sudomemo-locales to request support for Sudomemo. Rather, visit https://support.sudomemo.net.

Closing invalid

**Comment by crensyhanilas** [comment]
I cloae an issue. But...
