### ISSUE TITLE
Issue against. Error 340605

### ISSUE THREAD

**Issue by crensyhanilas** [Sudomemo/sudomemo-locales#121]
Damn bad weather! Please don't do it for nintendo team. For Support, Reply at https://github.com/Sudomemo/sudomemo-locales/issues/119#issuecomment-466636764sudofox for glitches.

- A Thanks at crensyhanilas

**Comment by sudofox** [comment]
Please don't use sudomemo-locales to request support for Sudomemo. Rather, visit https://support.sudomemo.net.

Closing invalid
