### ISSUE TITLE
Email footer text

### ISSUE THREAD

**Issue by Jean20B** [Sudomemo/sudomemo-locales#127]
![20190319_064747](https://user-images.githubusercontent.com/30441772/54583354-2d38a880-4a14-11e9-80f2-b0a2e67ba35b.jpg)

**Comment by crensyhanilas** [comment]
Me too, italian language glitches.

**Comment by sudofox** [comment]
The issue was that i was using the dailyStarReport locale for the email footer text by mistake, and when I made this commit - https://github.com/Sudomemo/sudomemo-locales/commit/b0c161fc76664838ecb31b941b490f86e7f66ed4 - it broke. I've fixed it now, sorry for the mistake.
