### ISSUE TITLE
Italian Language Glitches!!

### ISSUE THREAD

**Issue by ghost** [Sudomemo/sudomemo-locales#128]
![20190319_174410](https://user-images.githubusercontent.com/37714264/54625009-bb417d00-4a6e-11e9-8e4c-4335368c249e.jpg)

**Comment by sudofox** [comment]
I'll check into it

**Comment by sudofox** [comment]
Your locale is missing this: https://github.com/Sudomemo/sudomemo-locales/blob/master/en_US/LC_MESSAGES/channelList.po

```
[dev@devhost locale master $]# diff <(ls en_US/LC_MESSAGES/*.po|grep -Po "LC_MESSAGES/\K.*") <(ls it_IT/LC_MESSAGES/*.po|grep -Po "LC_MESSAGES/\K.*")
6d5
< channelList.po
16d14
< followNotificationEmail.po
```

Looks like you are missing those two files. The second one I introduced somewhat recently, so it may have been added after you started working on it.

**Comment by crensyhanilas** [comment]
I've added this pull request. If it merged, you can close and lock as resolved.

**Comment by crensyhanilas** [comment]
#131
