### ISSUE TITLE
September 2020 Translation Roundup: ja_JP

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#271]
# sudomemo-locales Problem Finder
Scans for problems as well as untranslated (or identical) strings
## ja_JP

ja_JP/LC_MESSAGES/browseChannel.po:
- BROWSE_BY_SONG
- BROWSE_BY_ARTIST
- BROWSE_BY_ALBUM
- BROWSE_PLAYLIST

ja_JP/LC_MESSAGES/common_ds.po:
- NOT_LOGGED_IN_NOTICE
- NOT_LOGGED_IN_NOTICE_LINK_TEXT
- YOU_HAVE_NEW_NOTIFICATIONS

ja_JP/LC_MESSAGES/creatorsRoom.po:
- PAGE_COUNTER_FORMAT

ja_JP/LC_MESSAGES/login.po:
- EMAIL_VERIFICATION_ADDRESS_REMOVED
- THANKS_FOR_LOGIN_PROMPT_INTRO
- PLEASE_DISCONNECT_AND_RECONNECT

ja_JP/LC_MESSAGES/mailSettings.po:
- TYPE_PROMO_NAME

ja_JP/LC_MESSAGES/musicMatch.po:
- HEADER_SONG_DETAILS
- TITLE
- ARTIST
- RELEASE_YEAR
- GENRE
- FLIPNOTE_COUNT
- BROWSE
- SONG_ID
- LINK_YOUTUBE_SPOTIFY
- LINK_YOUTUBE
- LINK_SPOTIFY
- IF_SONG_INCORRECT

ja_JP/LC_MESSAGES/profilePicture.po:
- LOGIN_REQUIRED_TO_CHANGE

ja_JP/LC_MESSAGES/reportContent.po:
- THANKS_FOR_REPORTING
- CATEGORY_NAME_stolen
- CATEGORY_DESC_stolen
- CATEGORY_NAME_spam
- CATEGORY_DESC_spam
- CATEGORY_NAME_harassment
- CATEGORY_DESC_harassment
- CATEGORY_NAME_fraud
- CATEGORY_DESC_fraud
- CATEGORY_NAME_swearing
- CATEGORY_DESC_swearing
- CATEGORY_NAME_sexual
- CATEGORY_DESC_sexual
- CATEGORY_NAME_violent
- CATEGORY_DESC_violent
- CATEGORY_NAME_misplaced_rp
- CATEGORY_DESC_misplaced_rp
- CATEGORY_NAME_drugs
- CATEGORY_DESC_drugs
- CATEGORY_NAME_rapid_flashing
- CATEGORY_DESC_rapid_flashing

ja_JP/LC_MESSAGES/theatre.po:
- MUSICMATCH
- NAVBAR_ITEM_DISCORD
- NAVBAR_ITEM_TWITTER
- NAVBAR_ITEM_INSTAGRAM
- NAVBAR_ITEM_FACEBOOK
- NAVBAR_ITEM_EMAIL
- NAVBAR_ITEM_ADMIN
- NAVBAR_ITEM_SUDOMEMO_ADMIN
- VIEWPAGE_RELATED_FLIPNOTE_BY
- NINTENDO_DSI
- NINTENDO_3DS
- YOUTUBE
- YOUTUBE_STATUS_TRACKER_NEW
- YOUTUBE_STATUS_FAILED_THUMB
- YOUTUBE_CHECK_FEATURES_THUMB
- YOUTUBE_REFRESH_ACCOUNT
- YOUTUBE_UNLINK_ACCOUNT
- YOUTUBE_UNLINK_ACCOUNT_CONFIRM

ja_JP/LC_MESSAGES/themeShop.po:
- NO_DESCRIPTION_AVAILABLE
- DETAILS

ja_JP/LC_MESSAGES/tickets.po:
- ACHIEVEMENT
- SUDOMEMO_PLUS

ja_JP/LC_MESSAGES/youtube.po:
- YOUTUBE
- YOUTUBE_STATUS_NEW
- ON
- OFF
- YOUTUBE_ID

**Comment by sudofox** [comment]
We've updated the locale files and fixed a lot of broken things. We'd ask that if you were already working on it to pull the latest version of the repository down and make sure to edit those instead, or else you'll have a merge conflict.

Some things to note:

- If there's any strings that are the same in the target language, please make a note that they should remain unchanged in your PR.
- We've added a header to help integrate some better tools for making the process more efficient. Do not change anything in the headers at the top of the file. It looks roughly like this:

```
msgid ""
msgstr ""
"Language: en_US\n"
"Content-Type: text/plain; charset=UTF-8\n"
```

- After the September translation roundup, we plan on starting to sort the files in alphabetical order, but haven't started yet.

Thanks!

**Comment by sudofox** [comment]
@nrhd @masatoshiko and @suraQ have all recently submitted partial translations. We do appreciate your contributions, but as we are doing a Roundup at this time we are only accepting completed translations. As such, please follow the steps in issue #282 until we've finished with our Roundup. Thank you very much :)

**Comment by sudofox** [comment]
Thank you to @suraQ for updating our translations. I did find a few remaining strings after pulling in your changes. If you could please update those ones, that'd be great. If the string is the same in Japanese as it is in English, please list it so I can add it to our ignore list.

# sudomemo-locales Problem Finder
Scans for problems as well as untranslated (or identical) strings

## ja_JP

ja_JP/LC_MESSAGES/browseFlipnotes.po:
- CATEGORY_feed

ja_JP/LC_MESSAGES/creatorsRoom.po:
- PAGE_COUNTER_FORMAT

ja_JP/LC_MESSAGES/theatre.po:
- MUSICMATCH
- NAVBAR_ITEM_DISCORD
- NAVBAR_ITEM_EMAIL
- NAVBAR_ITEM_FACEBOOK
- NAVBAR_ITEM_INSTAGRAM
- NAVBAR_ITEM_SUDOMEMO_ADMIN
- NAVBAR_ITEM_TWITTER
- NINTENDO_3DS
- NINTENDO_DSI
- VIEWPAGE_RELATED_FLIPNOTE_BY
- YOUTUBE
- YOUTUBE_STATUS_TRACKER_NEW

ja_JP/LC_MESSAGES/themeShop.po:
- NO_DESCRIPTION_AVAILABLE

ja_JP/LC_MESSAGES/tickets.po:
- ACHIEVEMENT
- SUDOMEMO_PLUS

ja_JP/LC_MESSAGES/youtube.po:
- OFF
- ON
- YOUTUBE
- YOUTUBE_ID
- YOUTUBE_STATUS_NEW

**Comment by suraQ** [comment]
MUSICMATCH
NAVBAR_ITEM_DISCORD
NAVBAR_ITEM_FACEBOOK
NAVBAR_ITEM_INSTAGRAM
NAVBAR_ITEM_SUDOMEMO_ADMIN
NAVBAR_ITEM_TWITTER
NINTENDO_3DS
NINTENDO_DSI
YOUTUBE
YOUTUBE_STATUS_TRACKER_NEW
OFF
ON
YOUTUBE
YOUTUBE_ID
YOUTUBE_STATUS_NEW

These words are easier for Japanese people to understand in English.

**Comment by sudofox** [comment]
Thank you very much :) With that, I think we've finished updates for Japanese! Thank you so much!

What is your Flipnote Studio ID?

**Comment by suraQ** [comment]
1DDED6C0CE8A0A3B
...Since the DSi has broken down, I plan to use it with 3DS in the future.

**Comment by sudofox** [comment]
Okay, so should we give the ticket to 1DDED6C0CE8A0A3B?

**Comment by suraQ** [comment]
Yes, Please.
