### ISSUE TITLE
September 2020 Translation Roundup

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#282]
Calling all translators! Calling all translators! We need your help!

We've created GitHub Issues for each of the languages currently set up for Sudomemo (except for English variants) along with a list of possible missing translations for each. Additional notes are at the end of the issue. We're hoping to get the site fully caught up by the end of the month. As a reminder, if you haven't already, reach out and we'll give you the Translator Ticket which gives you a special trophy and some stars as a reward.

We did put out some messaging requesting updates a bit prematurely, as we've made a lot of changes/fixes after closer inspection. If you've already started working on it, please stash your changes and pull down the latest version of Sudomemo/sudomemo-locales. 

**Please comment on the respective issue for your language to request claim over it if you plan to start working on it, so that we don't have people conflicting with each other. After doing so, you'll have three days to work before you either submit a completed translation or give up your claim for others to work.**

If you have any questions about certain translations while translating, please comment on the respective issue; however, once you submit your Pull Request, discussion should take place there instead.

As a reminder, while we use the word "translate" a lot here, what we want is actually localization, where cultural context in figures of speech can be adapted if need be to better help understanding. 

Below I'll be tagging everyone who's ever contributed in the past. Thanks for helping make Sudomemo more accessible, and Happy Flipnoting!

@sudofox @Jean20B @suraQ @NaoVolkova @SnowpMakes @sweirde @masatoshiko @knuxify @jaames @SlawomirNowak @fixfy @DavidTG9 @Ledtlalrtc @SlurpieDoo @SuperDuperRob @mnmannayw @thejsa @igantzia @KiMA38 @DarkSould04 @AbelSenpaiUwU @EDaniCB @Humitaxx @joffispresent @mrtnpwn @PLU4011 @dlrrCode @Suhbahstiejaan @TrashMe5951 @cruffle 

P.S. We're planning on localizing the Sudomemo Help Center soon, too, with the highest priority on Japanese. If you're interested, this does take more coordination than sudomemo-locales does, so please express your interest by leaving a comment with your Discord username on the original GitHub Issue for your language after submitting your completed work.

**Comment by sudofox** [comment]
We've completed updates for French, but there hasn't been any progress on any of the other languages.

**Comment by mrtnpwn** [comment]
I think I'll take care of the Spanish one. :smile:

**Comment by mrtnpwn** [comment]
Now that I'm looking carefully at the files, some of the Spanish strings feel kinda off... So I'll try to get the new ones done plus enhanced translations in one pull request, if that's OK, or two of them. Just let me know so I can start writing. :smile:

**Comment by sudofox** [comment]
@mrtnpwn So this weird thing happens every time someone comes along to look at the Spanish translation: they say about the exact same thing as you. Every time. I'm starting to wonder if this simply has something to do with different 'varieties' of Spanish from diff. parts of the world, such as Mexico/Spain or something? Could you explain?

**Comment by EDaniCB** [comment]
I don't really see any major problem, it's more than understandable, but if
you can enhance it it could be great! Go for it (I think lol).

**Comment by mrtnpwn** [comment]
> @mrtnpwn So this weird thing happens every time someone comes along to look at the Spanish translation: they say about the exact same thing as you. Every time. I'm starting to wonder if this simply has something to do with different 'varieties' of Spanish from diff. parts of the world, such as Mexico/Spain or something? Could you explain?

It has to do more with the use of punctuation and accentuation than the differences between 
Latin America/Spain "dialects" (which, in fact, are almost nil, as these are mostly regionalisms in top of castilian).

I think the fact that some sentences/words can't actually be translated (i.e. «Spin-Offs», «Sudomemo», «Flipnotes») also has to do with this.

**Comment by sudofox** [comment]
@mrtnpwn Please do feel free to claim the Spanish one and get it updated! Don't forget to note the msgid's that shouldn't be changed so I can mark them in the ignore list.

**Comment by Calvin2104** [comment]
CalvinRaye09#6146

**Comment by sudofox** [comment]
Hi Calvin, we've already completed Japanese. Thank you though :+1:

**Comment by Calvin2104** [comment]
Oh, ok. Anything else I can help with?
