### ISSUE TITLE
Patwa

### ISSUE THREAD

**Issue by ForsakenAstraldev** [Sudomemo/sudomemo-locales#320]
My langauge:Patios is not there,can you add it?

**Comment by ForsakenAstraldev** [comment]
Also I know japanesse! I think that I can help with that too.

**Comment by Katsufaux** [comment]
stinky

**Comment by ForsakenAstraldev** [comment]
> stinky

what stinky

**Comment by ForsakenAstraldev** [comment]
please tell me

**Comment by sudofox** [comment]
@ForsakenAstraldev Ignore it

**Comment by ForsakenAstraldev** [comment]
ok

**Comment by Katsufaux** [comment]
kek

**Comment by ForsakenAstraldev** [comment]
What's kek

**Comment by ForsakenAstraldev** [comment]
Oh wait kek means lol,can you tell me what's funny? I think I can understand if you tell me

**Comment by sudofox** [comment]
Terribly sorry for the delay on this. We've been backed up with stuff. Expect an update by this weekend, and thank you for your enthusiasm!

**Comment by sudofox** [comment]
Hi, we're putting new languages on hold until we can get the whole repo fully updated.

We're also going to be doing demographic analysis to see expected usage as well prior to adding new languages.

Sorry about that.
