### ISSUE TITLE
Polish language is broken on console

### ISSUE THREAD

**Issue by Szprinktrap** [Sudomemo/sudomemo-locales#321]
Polish language has special characters, such as ż, ć, ł, ą etc. 
Flipnote Studio font don't have these and places where they should go are empty. 
Here are some examples of that occurring:
![IMG_20201115_085310](https://user-images.githubusercontent.com/29673535/99180272-0ff63900-2725-11eb-85bf-039f0e837971.png)
![IMG_20201115_084825](https://user-images.githubusercontent.com/29673535/99180300-606d9680-2725-11eb-8be1-f43fc3aa6fad.png)
![IMG_20201115_084753](https://user-images.githubusercontent.com/29673535/99180302-64011d80-2725-11eb-8453-afd22743838e.png)
![IMG_20201115_084722](https://user-images.githubusercontent.com/29673535/99180304-6a8f9500-2725-11eb-8b4d-55ecf96d8e87.png)
![IMG_20201115_084649](https://user-images.githubusercontent.com/29673535/99180308-6cf1ef00-2725-11eb-8c2a-607098d3af2a.png)

**Comment by sudofox** [comment]
What would work as an alternative? I can't add new glyphs to the font unfortunately

**Comment by Szprinktrap** [comment]
Replacing them with standard letters, for example ś > s, ż > z

**Comment by sudofox** [comment]
Sure, I'll look into doing that further. Here's what you can do to help:

- Write a comment on Sudomemo with all the special letters that you can think of and then let me know which ones don't render properly.
- I can push an update that replaces these special characters as well as adds a comment for future translators

**Comment by Szprinktrap** [comment]
Just tried it out, apparently only ó renders properly.
So, the affected characters + replacements are:
ą > a
ś > s
ż > z
ź > z
ć > c
ł > l

**Comment by sudofox** [comment]
I assume uppercase versions would need updating as well?

**Comment by Szprinktrap** [comment]
Most likely, yeah.

**Comment by knuxify** [comment]
The best way to handle this would probably be to update strings that are displayed on the console to use non-polish counterparts, while leaving the strings for the website intact. This would mean that we'd need to figure out which strings are used where, though.
