### ISSUE TITLE
Request to add sk_SK and cs_CZ Langcodes for translation

### ISSUE THREAD

**Issue by Matejono** [Sudomemo/sudomemo-locales#353]
I would like to request the addition of a Slovak and Czech Langcode so a proper translation is availiable.

**Comment by meemo** [comment]
Looking through examples of these languages, it looks like there are some common characters like š and č that aren't able to be rendered by the DSi. Would text still be readable if those characters were replaced with a character that doesn't have the accent? i.e. č -> c, š -> s.

**Comment by Matejono** [comment]
> Looking through examples of these languages, it looks like there are some common characters like š and č that aren't able to be rendered by the DSi. Would text still be readable if those characters were replaced with a character that doesn't have the accent? i.e. č -> c, š -> s.

Yeah, it would be perfectly understandable, since we dont use diacritics that much for text messages.

**Comment by meemo** [comment]
Awesome! Send a DM to SudoModMail on the [Sudomemo Discord](https://flipnot.es/discord) and we'll help you get set up!

**Comment by Lennoxrobot99** [comment]
Hallo, ich möchte eine neue Sprache hinzufügen Japanisch.

**Comment by meemo** [comment]
> Hallo, ich möchte eine neue Sprache hinzufügen Japanisch.

Hello, Japanese is already a translated language and is effectively complete last I checked. If there is a specific issue or if you would like to add that isn't already translated then please open a new issue.

**Comment by meemo** [comment]
Closing due to lack of maintainers.
