### ISSUE TITLE
Request to add tr-TR for translation.

### ISSUE THREAD

**Issue by Grandmaquil** [Sudomemo/sudomemo-locales#390]
I would like to translate to turkish.

**Comment by meemo** [comment]
Hello! Thank for the offer! There should be no issues with adding Turkish, so check out https://github.com/Sudomemo/sudomemo-locales#how-to-contribute when you're ready to contribute!

Would you mind joining [the Sudomemo Discord](https://flipnot.es/discord) and sending SudoModMail a DM?

**Comment by Grandmaquil** [comment]
i am already in the sudomemo server what do i need to send sudo mod mail

5 May 2022 Per 01:41 tarihinde Meemo4556 ***@***.***> şunu
yazdı:

**Comment by meemo** [comment]
Send a message saying you're here from GitHub and would like to translate Turkish, we will send you an invite to the translator server.

**Comment by meemo** [comment]
Closing as tr_TR was added.
