### ISSUE TITLE
Updates needed: ja_JP

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#396]
## ja_JP

If you haven't contributed in a while, please re-familiarize yourself with the process, including Ignore Lists:

https://github.com/Sudomemo/sudomemo-locales/blob/master/README.md

Please comment here and we will assign you to this issue.

If I haven't tagged you here, that means that you have not placed your GitHub username in the #github-username channel in the Sudomemo Translators Discord server. If you are not in this server, please reach out to SudoModMail in the Sudomemo Discord to be added.

@RYU-N2001 
```
ja_JP/LC_MESSAGES/discordbot.po:
REJECT_BOOST_TICKET_COOLDOWN
UNLINKED_COMMAND_TIP
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

ja_JP/LC_MESSAGES/flipnoteComments.po:
SUDOMEMO_USER

ja_JP/LC_MESSAGES/passwordValidator.po:
PASS_CHANGE_ERROR_CONFIRM_NO_MATCH
PASS_CHANGE_ERROR_LEAD_TRAIL_WHITESPACE
PASS_CHANGE_ERROR_LENGTH
PASS_CHANGE_ERROR_LOWERCASE
PASS_CHANGE_ERROR_MATCHES_EMAIL
PASS_CHANGE_ERROR_MATCHES_FSID
PASS_CHANGE_ERROR_NUMBER
PASS_CHANGE_ERROR_SPECIAL
PASS_CHANGE_ERROR_TOO_COMMON
PASS_CHANGE_ERROR_TYPEABLE
PASS_CHANGE_ERROR_UPPERCASE
PASS_CHANGE_RESTRICTED_CHARS

ja_JP/LC_MESSAGES/theatre.po:
ARCHIVE
ARCHIVED
ARCHIVE_FLIPNOTE
ARCHIVE_FLIPNOTE_DESC
ARCHIVE_PROFILE
ARCHIVE_PROFILE_DESC
DISCORD
FLIPNOTE_ARCHIVE_BUTTON_TOGGLE
FLIPNOTE_ARCHIVE_PROFILE_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_NOT_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_SETTING_INFORMATION
FLIPNOTE_ARCHIVE_SETTINGS
FLIPNOTE_HATENA_PROFILE
LEARN_MORE
SUDOMEMO_USER
USERS_FLIPNOTE_FROM_FLIPNOTE_HATENA
USERS_PROFILE_FROM_FLIPNOTE_HATENA
VIEW_ON_SUDOMEMO

ja_JP/LC_MESSAGES/tickets.po:
TICKET_DESC_8th_birthday_bash_ticket
TICKET_NAME_8th_birthday_bash_ticket

ja_JP/LC_MESSAGES/trophies.po:
TROPHY_DESC_8th_birthday_bash
TROPHY_NAME_8th_birthday_bash
```

**Comment by sjkim04** [comment]
- `UNLINKED_COMMAND_TIP` in `discordbot.po`
  - I think we need to add a placeholder for the command, as the command `.sudo link` will come at first.

**Comment by sjkim04** [comment]
You know what, I’ll just add it in my next PR

**Comment by meemo** [comment]
For `UNLINKED_COMMAND_TIP`, is there no way to make it make sense with the command after the text?

**Comment by sjkim04** [comment]
There is a way to do it:
`You can link a Sudomemo account with the following command: `

..but it sounds awkward.

**Comment by meemo** [comment]
I think it would be best this way, as it won't show up very frequently and a placeholder would involve reworking every locale to reflect this.

@sudofox Thoughts?
