### ISSUE TITLE
Updates needed: es_ES

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#398]
## es_ES

If you haven't contributed in a while, please re-familiarize yourself with the process, including Ignore Lists:

https://github.com/Sudomemo/sudomemo-locales/blob/master/README.md

Please comment here and we will assign you to this issue.

If I haven't tagged you here, that means that you have not placed your GitHub username in the #github-username channel in the Sudomemo Translators Discord server. If you are not in this server, please reach out to SudoModMail in the Sudomemo Discord to be added.

@MafiaGamesCoder @meemo

```
es_ES/LC_MESSAGES/discordbot.po:
REJECT_BOOST_TICKET_COOLDOWN
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

es_ES/LC_MESSAGES/theatre.po:
ARCHIVE
ARCHIVED
ARCHIVE_FLIPNOTE
ARCHIVE_FLIPNOTE_DESC
ARCHIVE_PROFILE
ARCHIVE_PROFILE_DESC
FLIPNOTE_ARCHIVE_BUTTON_TOGGLE
FLIPNOTE_ARCHIVE_PROFILE_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_NOT_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_SETTING_INFORMATION
FLIPNOTE_ARCHIVE_SETTINGS
FLIPNOTE_HATENA_PROFILE
LEARN_MORE
USERS_FLIPNOTE_FROM_FLIPNOTE_HATENA
USERS_PROFILE_FROM_FLIPNOTE_HATENA
VIEW_ON_SUDOMEMO

es_ES/LC_MESSAGES/tickets.po:
TICKET_DESC_8th_birthday_bash_ticket
TICKET_NAME_8th_birthday_bash_ticket

es_ES/LC_MESSAGES/trophies.po:
TROPHY_DESC_8th_birthday_bash
TROPHY_NAME_8th_birthday_bash
```

**Comment by meemo** [comment]
Done in #422
