### ISSUE TITLE
Updates needed: fr_FR

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#399]
## fr_FR

If you haven't contributed in a while, please re-familiarize yourself with the process, including Ignore Lists:

https://github.com/Sudomemo/sudomemo-locales/blob/master/README.md

Please comment here and we will assign you to this issue.

If I haven't tagged you here, that means that you have not placed your GitHub username in the #github-username channel in the Sudomemo Translators Discord server. If you are not in this server, please reach out to SudoModMail in the Sudomemo Discord to be added.

@Jean20B 

```
fr_FR/LC_MESSAGES/discordbot.po:
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

fr_FR/LC_MESSAGES/theatre.po:
DISCORD
```

**Comment by Jean20B** [comment]
For theatre.po : #405 

I think discordbot.po is already translated, did I miss something?

**Comment by sudofox** [comment]
Looks like we've rediscovered an old bug with the script that checks for untranslated strings, don't worry about it for now
