### ISSUE TITLE
Updates needed: it_IT

### ISSUE THREAD

**Issue by sudofox** [Sudomemo/sudomemo-locales#403]
## it_IT

If you haven't contributed in a while, please re-familiarize yourself with the process, including Ignore Lists:

https://github.com/Sudomemo/sudomemo-locales/blob/master/README.md

Please comment here and we will assign you to this issue.

If I haven't tagged you here, that means that you have not placed your GitHub username in the #github-username channel in the Sudomemo Translators Discord server. If you are not in this server, please reach out to SudoModMail in the Sudomemo Discord to be added.

@guido-pavesi 

```
it_IT/LC_MESSAGES/theatre.po:
ARCHIVE
ARCHIVED
ARCHIVE_FLIPNOTE
ARCHIVE_FLIPNOTE_DESC
ARCHIVE_PROFILE
ARCHIVE_PROFILE_DESC
FLIPNOTE_ARCHIVE_BUTTON_TOGGLE
FLIPNOTE_ARCHIVE_PROFILE_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_NOT_AVAILABLE
FLIPNOTE_ARCHIVE_PROFILE_SETTING_INFORMATION
FLIPNOTE_ARCHIVE_SETTINGS
FLIPNOTE_HATENA_PROFILE
LEARN_MORE
USERS_FLIPNOTE_FROM_FLIPNOTE_HATENA
USERS_PROFILE_FROM_FLIPNOTE_HATENA
VIEW_ON_SUDOMEMO

it_IT/LC_MESSAGES/tickets.po:
TICKET_DESC_8th_birthday_bash_ticket
TICKET_NAME_8th_birthday_bash_ticket

it_IT/LC_MESSAGES/trophies.po:
TROPHY_DESC_8th_birthday_bash
TROPHY_NAME_8th_birthday_bash
```

**Comment by sudofox** [comment]
Tagging @PincoPaolo as well. If you or @guido-pavesi want to work on this one, leave a comment and I'll assign it to you.

**Comment by guido-pavesi** [comment]
@sudofox I'll work on this one :)

**Comment by sudofox** [comment]
sounds good! assigned

**Comment by guido-pavesi** [comment]
Hi. I'm checking the new strings right now. I have a question about the file theatre.po: is the string named ARCHIVED referring to multiple flipnotes or only one?
