### ISSUE TITLE
Sudomemo new language. 

### ISSUE THREAD

**Issue by Lennoxrobot99** [Sudomemo/sudomemo-locales#467]
Japan is the new language.

**Comment by meemo** [comment]
Japanese is already a fully translated language.

**Comment by Lennoxrobot99** [comment]
No,that is not in the language inside add Japan please.

**Comment by meemo** [comment]
Are you talking about the default displayed language in Sudomemo? Sudomemo defaults to whatever language your console is currently using, but this can be changed at the bottom of your Creator's Room. Again, Japanese is an added language so we can't just "add it again."
