### ISSUE TITLE
Request to add hr_HR (Croatian)

### ISSUE THREAD

**Issue by despawnedd** [Sudomemo/sudomemo-locales#474]
I'd like to translate stuff to Croatian. 

Just a note: I think that diacritics could be an issue here; however, excluding them should not cause a big decrease in readability. (see #353 - similar problem)

**Comment by Tescu48** [comment]
Hi there! Im the Romanian translator for the app. I have been having the same issues with the diacritics. Everything but the theatre and discordbot should be done without diacritics. For the two afformentioned ones you can use the diacritics just fine. Hope I helped.

**Comment by despawnedd** [comment]
In the Sudomemo Translators server I've announced that I give up with this (at least for now), so I'm closing this
